---
- hosts: all
  remote_user: ubuntu

  tasks: 
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Openjdk repo
      become: yes
      apt_repository: repo='ppa:openjdk-r/ppa'

    - name: Install openjdk 8 p1
      become: yes
      apt: name=openjdk-8-jre
    
    - name: echo
      become: yes
      shell: java -version
    
    - name: Copy using inline content
      become: yes
      copy:
        content: ../target/heretoclean-0.0.1-SNAPSHOT.jar
        dest: /home/heretoclean-0.0.1-SNAPSHOT.jar
    
    - name: run
      become: yes
      shell: cd /home/ && nohup java -jar heretoclean-0.0.1-SNAPSHOT.jar &